name: 03 - using-actions

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: 03-using-actions
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: '24.x'
            - name: install dependencies
              run: npm install