name: 03-using-actions

on:
    push:

jobs:
    build:
        runs-on: ubunto-latest
        steps:
            - name: checkout code
              uses: actions/checkout@4
            - name: printing folders
              run: ls