name: 03 - using-actions

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: '24.x'
            - name: install dependencies
              run: npm install