name: 06 - contexts
run-name: Test The inputs feature  ${{ inputs.name }}
on:
    push:
    workflow_dispatch:
        inputs:
           name:
            type: string
            default: "yassine is calling"
    
      

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Display informations
              run: |
                echo "Event name: ${{ github.event_name}}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run number: ${{ github.run_number }}"

            - name: Retreive Variable
              run: |
                echo "Variable value: ${{vars.MY_VARIABLE}} "
            