name: 11 - Using caching

on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: Whether to execture cache step
                type: boolean
                default: true
            

jobs: 
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: react-app
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5
            - name: Steup Node
              uses: actions/setup-node@v5
              with:
                node-version: '24.x'
            - name: Install dependencies
              run: npm i
            
            - name: Building
              run: npm run build
            
            - name: Deploy to nonprod
              run: echo "Deploying to Non prod..."
            
            
            

            



        

