name: 11 - Using caching

on:
    workflow_dispatch:
      inputs:
        use-cache:
            description: build by using caching.
            type: boolean
            default: false

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: react-app
        
        steps:
            - name: Checkout the code
              uses: actions/checkout@v5

            - name: Setup Node version
              uses: actions/setup-node@v5
              with:
                node-version: '24.x'
            
            - name: Download cached dependencies
              uses: actions/cache@v5
              if: ${{ inputs.use-cache}}
              id: cache
              with:
                path: react-app/node_modules
                key: deps-node-cache-${{ hashFiles('react-app/package-lock.json')}}
            
            - name: Install dependencies
              if: ${{steps.cache.outputs.cache-hit != 'true'}}
              run: npm i
            - name: Build
              run: npm run build
            
            - name: Deploy to non prod
              run: echo "App is deploying..."

